"""Remove prefix to advisors

Revision ID: 2bfdaf4f9b5f
Revises: b2db36bdf5ab
Create Date: 2025-03-27 21:07:26.230860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfdaf4f9b5f'
down_revision = 'b2db36bdf5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.drop_column('prefix')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
