"""Increase password field size

Revision ID: 421535d5ed24
Revises: 9e6fdcdeacb2
Create Date: 2025-03-17 23:19:53.280854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421535d5ed24'
down_revision = '9e6fdcdeacb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
