"""Add note column to availabilities

Revision ID: 537eda6e1f80
Revises: 3418ddbc6089
Create Date: 2025-03-27 19:39:40.037725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537eda6e1f80'
down_revision = '3418ddbc6089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
