"""Delete avail cascade again

Revision ID: 608d6b1a8aac
Revises: f3f2fce94962
Create Date: 2025-04-06 20:43:44.138625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608d6b1a8aac'
down_revision = 'f3f2fce94962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.drop_constraint('availabilities_advisor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'advisors', ['advisor_id'], ['advisor_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('availabilities_advisor_id_fkey', 'advisors', ['advisor_id'], ['advisor_id'])

    # ### end Alembic commands ###
