"""Add cascade delete to appointments

Revision ID: 632aeb04b8a1
Revises: 7c09a0608258
Create Date: 2025-04-26 19:45:58.954630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632aeb04b8a1'
down_revision = '7c09a0608258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('appointments_advisor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'advisors', ['advisor_id'], ['advisor_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointments_advisor_id_fkey', 'advisors', ['advisor_id'], ['advisor_id'])

    # ### end Alembic commands ###
