"""Add cascade delete to notes

Revision ID: 8554bfd20a57
Revises: 632aeb04b8a1
Create Date: 2025-04-26 19:50:40.477261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8554bfd20a57'
down_revision = '632aeb04b8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('appointment_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.drop_constraint('notes_appointment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['appointment_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notes_appointment_id_fkey', 'appointments', ['appointment_id'], ['appointment_id'])
        batch_op.alter_column('appointment_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
