"""Add new columns to the appointments table

Revision ID: 893f0603ce2a
Revises: b77fc5806eeb
Create Date: 2025-04-03 19:37:26.694133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893f0603ce2a'
down_revision = 'b77fc5806eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('student_last_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('student_last_name')
        batch_op.drop_column('student_name')

    # ### end Alembic commands ###
