"""Add new columns to the appointments table

Revision ID: ab3cfcf83110
Revises: b120cffc2401
Create Date: 2025-04-01 09:16:36.709008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3cfcf83110'
down_revision = 'b120cffc2401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advisor_last_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('advisor_last_name')

    # ### end Alembic commands ###
