"""Add new columns to the appointments table

Revision ID: b120cffc2401
Revises: 2bfdaf4f9b5f
Create Date: 2025-04-01 09:15:07.472514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b120cffc2401'
down_revision = '2bfdaf4f9b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advisor_email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('advisor_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('advisor_office', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('advisor_office')
        batch_op.drop_column('advisor_name')
        batch_op.drop_column('advisor_email')

    # ### end Alembic commands ###
