"""Add prefix to advisors

Revision ID: b2db36bdf5ab
Revises: 537eda6e1f80
Create Date: 2025-03-27 19:43:07.582722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2db36bdf5ab'
down_revision = '537eda6e1f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.drop_column('prefix')

    # ### end Alembic commands ###
