"""Add new columns to the appointments table

Revision ID: b77fc5806eeb
Revises: ab3cfcf83110
Create Date: 2025-04-01 20:33:01.896431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77fc5806eeb'
down_revision = 'ab3cfcf83110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_email', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('student_email')

    # ### end Alembic commands ###
