"""Add new columns to the appointments table

Revision ID: eff8e0254809
Revises: 893f0603ce2a
Create Date: 2025-04-05 12:59:03.093763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff8e0254809'
down_revision = '893f0603ce2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('reset_code')

    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.drop_column('reset_code')

    with op.batch_alter_table('administration', schema=None) as batch_op:
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
