name: Test

on:
  push:
    branches: [ temp ]
  pull_request:
    branches: [ temp ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    defaults:
    
    steps:
    - name: Checkout Code
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip
      
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
        python -m nltk.downloader punkt wordnet averaged_perceptron_tagger
        
    - name: Download NLTK data
      run: |
        python -c "import nltk; nltk.download('punkt'); nltk.download('wordnet')"

    - name: Run Flask tests
      run: |
        pytest tests/
        
